apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: microservice-demo
  labels:
    app: microservices-demo
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: microservice-demo
  labels:
    app: microservices-demo
spec:
  selector:
    app: productcatalogservice
  ports:
    - name: http
      port: 3550
      targetPort: 3550
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: microservice-demo
  labels:
    app: microservices-demo
spec:
  selector:
    app: cartservice
  ports:
    - name: http
      port: 7070
      targetPort: 7070 